[main]
user = mk.com.snt.kc.warehouse.view.security.FacesAjaxAwareUserFilter
user.loginUrl = /login
anyrole = mk.com.snt.kc.warehouse.view.security.AnyRoleAuthorizationFilter

[urls]
/login = user
/home = user
/home.xhtml = user
/daily_exits = user
/daily_exits.xhtml = user
/report = user
/report.xhtml = user
#/report1 = user
#/report1.xhtml = user
/excel = user
/excel.xhtml = user
/admin/** = user, anyrole[ROLE_ADMIN]